### ISSUE TITLE
system-cloudinit@-var-tmp-hostname.yml.service fails

### ISSUE THREAD

**Issue by theRemix** [coreos/coreos-vagrant#242] opened 2015-06-12 07:49 UTC
I'm not sure if this is a coreos-vagrant issue, coreos issue, vagrant issue, virtualbox issue, or osx issue.

1) when i `vagrant up` my coreos-vagrant box, it prompts me for password

```
$ vagrant up
Bringing machine 'core-01' up with 'virtualbox' provider...
==> core-01: Clearing any previously set forwarded ports...
==> core-01: Clearing any previously set network interfaces...
==> core-01: Preparing network interfaces based on configuration...
    core-01: Adapter 1: nat
    core-01: Adapter 2: hostonly
==> core-01: Forwarding ports...
    core-01: 22 => 2222 (adapter 1)
==> core-01: Running 'pre-boot' VM customizations...
==> core-01: Booting VM...
==> core-01: Waiting for machine to boot. This may take a few minutes...
    core-01: SSH address: 127.0.0.1:2222
    core-01: SSH username: core
    core-01: SSH auth method: private key
    core-01: Warning: Connection timeout. Retrying...
Text will be echoed in the clear. Please install the HighLine or Termios libraries to suppress echoed text.
core@127.0.0.1's password:
```

2) when i do login (using cleartext password), i get this error

```
==> core-01: Machine booted and ready!
==> core-01: Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

systemctl start system-cloudinit@-var-tmp-hostname.yml.service

Stdout from the command:



Stderr from the command:

Job for system-cloudinit@-var-tmp-hostname.yml.service failed because a configured resource limit was exceeded. See "systemctl status system-cloudinit@-var-tmp-hostname.yml.service" and "journalctl -xe" for details.
```

3) when i finally get in somehow, my shared/synced folders are no longer shared.

my biggest problem is that i cannot get shared folders to work.  
i've been using coreos-vagrant for a long time without any issues.   
i did a `vagrant box update` and nothing changed.  
when i spin up a brand new machine, i have the same problems.  
my wife works with me, and her coreos-vagrant is also now having the same issues.

has anyone ever experienced problems like this?

`coreos-alpha  (virtualbox, 709.0.0)`

**Comment by crawford** [comment] 2015-06-12 07:57
Duplicate of https://github.com/coreos/bugs/issues/382.

**Closed by crawford** 2015-06-12 07:57 UTC

**Comment by theRemix** [comment] 2015-06-12 21:03
@crawford this has been fixed in the overlay. how do i apply the fix to my vagrant box?

**Comment by crawford** [comment] 2015-06-12 22:37
You can either build an image from source or use one of the older images. We will roll out a fix for this in about a week.

**Comment by morgante** [comment] 2015-06-14 01:11
How do I build the image from scratch?

**Comment by crawford** [comment] 2015-06-14 02:05
The instructions for building an image can be found [here](https://coreos.com/docs/sdk-distributors/sdk/modifying-coreos/). It will be much faster if you just use a Beta or Stable image for the time being.

**Comment by theRemix** [comment] 2015-06-14 19:23
@morgante i just rolled back my update and was able to work again.
see instructions on rolling back to the previous version here: https://coreos.com/docs/cluster-management/debugging/manual-rollbacks/

**Comment by morgante** [comment] 2015-06-14 19:24
@theRemix Thanks for the tip, I ended up switching to the stable channel for now.
