### ISSUE TITLE
Starting vagrant results in error

### ISSUE THREAD

**Issue by johscheuer** [coreos/coreos-vagrant#246] opened 2015-06-18 08:03 UTC
Hey,

I cloned the git repo and modified the config.rb to start 3 instances and in the user-data I enabled etcd2 and created a new discovery token. When I try to start the boxes now I get an error:

```Bash
==> core-01: Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

systemctl start system-cloudinit@-var-tmp-hostname.yml.service

Stdout from the command:



Stderr from the command:

Job for system-cloudinit@-var-tmp-hostname.yml.service failed because a configured resource limit was exceeded. See "systemctl status system-cloudinit@-var-tmp-hostname.yml.service" and "journalctl -xe" for details.
```

The content of the system-cloudinit@-var-tmp-hostname.yml.service is:
```Bash
core@localhost ~ $ systemctl cat system-cloudinit@-var-tmp-hostname.yml.service
# /usr/lib64/systemd/system/system-cloudinit@.service
[Unit]
Description=Load cloud-config from %f
Requires=dbus.service
After=dbus.service
Before=system-config.target
ConditionFileNotEmpty=%f

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/coreos-cloudinit --from-file=%f
```

and jorunalctl says %f is an invalid argument
```Bash
core@localhost ~ $ journalctl -u system-cloudinit@-var-tmp-hostname.yml.service
-- Logs begin at Thu 2015-06-18 07:50:01 UTC, end at Thu 2015-06-18 07:53:16 UTC. --
Jun 18 07:50:12 localhost systemd[1]: [/usr/lib64/systemd/system/system-cloudinit@.service:2] Failed to resolve unit specifiers on Load cloud-config from %f, ignoring: Invalid argument
Jun 18 07:50:12 localhost systemd[1]: [/usr/lib64/systemd/system/system-cloudinit@.service:6] Failed to resolve specifiers, ignoring: %f
Jun 18 07:50:12 localhost systemd[1]: system-cloudinit@-var-tmp-hostname.yml.service: Failed to run 'start' task: Invalid argument
Jun 18 07:50:12 localhost systemd[1]: Failed to start system-cloudinit@-var-tmp-hostname.yml.service.
Jun 18 07:50:12 localhost systemd[1]: system-cloudinit@-var-tmp-hostname.yml.service: Unit entered failed state.
Jun 18 07:50:12 localhost systemd[1]: system-cloudinit@-var-tmp-hostname.yml.service: Failed with result 'resources'.
Jun 18 07:50:12 localhost systemd[1]: Starting system-cloudinit@-var-tmp-hostname.yml.service...
```

and systemctl status prints of course the same:
```Bash
core@localhost ~ $ systemctl status system-cloudinit@-var-tmp-hostname.yml.service 
● system-cloudinit@-var-tmp-hostname.yml.service
   Loaded: loaded (/usr/lib64/systemd/system/system-cloudinit@.service; static; vendor preset: disabled)
   Active: failed (Result: resources)

Jun 18 07:50:12 localhost systemd[1]: [/usr/lib64/systemd/system/system-cloudinit@.service:2] Failed to resolve unit specifiers on Load cloud-config from %f, ignoring: Invalid argument
Jun 18 07:50:12 localhost systemd[1]: [/usr/lib64/systemd/system/system-cloudinit@.service:6] Failed to resolve specifiers, ignoring: %f
Jun 18 07:50:12 localhost systemd[1]: system-cloudinit@-var-tmp-hostname.yml.service: Failed to run 'start' task: Invalid argument
Jun 18 07:50:12 localhost systemd[1]: Failed to start system-cloudinit@-var-tmp-hostname.yml.service.
Jun 18 07:50:12 localhost systemd[1]: system-cloudinit@-var-tmp-hostname.yml.service: Unit entered failed state.
Jun 18 07:50:12 localhost systemd[1]: system-cloudinit@-var-tmp-hostname.yml.service: Failed with result 'resources'.
Jun 18 07:50:12 localhost systemd[1]: Starting system-cloudinit@-var-tmp-hostname.yml.service...
```

Vagrant stops when the first machine is up, I can also login but nothing is configured and my other two machines doesn't get started. 

Thanks for your help!

**Comment by crawford** [comment] 2015-06-18 08:04
Duplicate of https://github.com/coreos/bugs/issues/386.

**Closed by crawford** 2015-06-18 08:04 UTC
