### ISSUE TITLE
Beta 899.1.0 missing Vagrant image

### ISSUE THREAD

**Issue by romesh-mccullough** [coreos/coreos-vagrant#279] opened 2016-01-14 16:47 UTC
It appears that the vagrant boxes are missing from http://beta.release.core-os.net/amd64-usr/899.1.0/.  Stable and Alpha look ok.

Thanks!

**Comment by crawford** [comment] 2016-01-14 16:50
Duplicate of https://github.com/coreos/bugs/issues/1075.

**Closed by crawford** 2016-01-14 16:50 UTC
